### ISSUE TITLE
Purchase Shards

### ISSUE THREAD

**Issue by NikHerdt** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_002#14]
As a user I want to be able to view a shards purchase option on the worlds browser page.
As a user I want to be able to purchase shards with my choice of real-world currency via a credit/debit card transaction.
* Shards = 0.75 USD
* Can be converted from USD, CAD, GBP, Euro or JPY

**Comment by adervesh03** [comment]
currency conversion done, integration tests pending purchase page views
