### ISSUE TITLE
Play Mini Game

### ISSUE THREAD

**Issue by NikHerdt** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_002#15]
As a player I want to be able to, when available, play a mini game as my game action. Shards can be won by putting in shards and winning back a multiple.
Minigame options:
 - Blackjack
 - Dice
 - Roulette

**Comment by adervesh03** [comment]
users can play mini games at each cell, but each cell has a randomized "buy-in" or amount of shards they put at stake.
