### ISSUE TITLE
Game Shop

### ISSUE THREAD

**Issue by NikHerdt** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_002#17]
As a user I should be able use my shards to purchase items in the shop. Some items for purchase:
* XP booster (boosts xp gain from quests by 1.25)
* item to move past adjacent squares
* item to increase mini game luck

**Comment by adervesh03** [comment]
join tables created for items/shops, users/items, and grids/shops

**Comment by tannguyen912** [comment]
The db ER should looks something like this
![Image](https://github.com/user-attachments/assets/e4bdf4a0-210e-43bf-aee8-a39ced77165e)

**Comment by adervesh03** [comment]
updating this ticket to ignore shops, will simulate a shop view and let users buy items directly, will only use the item and inventory_item db's from now on.

The xp boost item that boosts xp gain will need to wait until nik finishes his task to be implemented
