### ISSUE TITLE
Fix the shards

### ISSUE THREAD

**Issue by gg9192** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_002#64]
As a user, I want the shards DB to be fixed, so that I can get charged the correct amount.

Currently, shards amount is an int. Change the shards system where 100 shards in the DB reflects as 1.00 for the user. This is important because hans says that any move is 0.75 shards, but in the current system, it rounds to the nearest int, so they get charged 1

**Comment by adervesh03** [comment]
This does not need to necessarily be fixed now, as the project described:
"Moving to adjacent squares is free, while moving to any non-adjacent square costs at least 0.25 Shards (you may have other dynamic costs of more than this amount)."

This means we can make the non-adjacent movement exactly 1 shard if we want

**Comment by tannguyen912** [comment]
Close this issue and move all the decimal UI text to the issue #60.
